title: Hello
description: <a href="https://www.deviantart.com/defeg" target="_blank">Art</a> <br />  <a href="https://dgoekmen.github.io/Statistical-Mechanics/" target="_blank">Satistical mechanics notebooks</a> <br /> <a href="https://www.researchgate.net/profile/Doruk_Goekmen/" target="_blank">ResearchGate profile</a>
theme: jekyll-theme-minimal
