title: Hello
description: <a href="https://dgoekmen.github.io/Statistical-Mechanics/" target="_blank">Statistical mechanics notebooks</a> <br /> <a href ="https://dgoekmen.github.io/Schrodinger-equation-solver/" target="blank">Schrödinger equation solver</a> <br /> <a href="https://www.researchgate.net/profile/Doruk_Goekmen/" target="_blank">ResearchGate profile</a> <br /> <a href="https://www.deviantart.com/defeg" target="_blank">Art</a>  
theme: jekyll-theme-minimal
